### ISSUE TITLE
editor_assets folder is missing

### ISSUE THREAD

**Issue by gooigi74** [Mitchell1711/pt-cyop#3]
everytime i open this build i keep getting that error
![image](https://github.com/Mitchell1711/pt-cyop/assets/86253866/f0c0664b-8e1a-4c1a-91ed-18873e5ef9f8)

**Comment by snoopi64** [comment]
Install the "data" folder listed within the source code, then place the "editor_assets" folder in the "PizzaTower_GM2" located in appdata, which can be accessed by opening the "Run" command and typing "%appdata%" (so it would look something like C:\Users\*Computer Name Here*\AppData\Roaming\PizzaTower_GM2\editor_assets). Make sure the folder is extracted completely and has all of its files contained in a singular folder (instead of "\editor_assets\editor_assets\" it should be "\editor_assets").
